# Generated by Django 2.2.7 on 2019-11-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='corre',
            new_name='correo',
        ),
    ]
