# Generated by Django 2.2.7 on 2019-11-14 01:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editoriales', '0001_initial'),
        ('autores', '0002_auto_20191113_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(default=datetime.datetime(2019, 11, 14, 1, 35, 38, 321798, tzinfo=utc))),
                ('autores', models.ManyToManyField(to='autores.Autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editoriales.Editorial')),
            ],
        ),
    ]
